AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance for OpenSupports Application

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
