
AWSTemplateFormatVersion: "2010-09-09"
Description: RDS MySQL Instance for OpenSupports

Parameters:
  DBName:
    Type: String
    Default: opensupportsdb
  DBUser:
    Type: String
    Default: admin
  DBPassword:
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41

Resources:
  MySQLDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      EngineVersion: "8.0"
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      PubliclyAccessible: false
      MultiAZ: false

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/16 # Restrict to VPC CIDR
