AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket for storing static files

Resources:
  StaticFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'opensupports-static-${AWS::StackName}'
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

