AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket for storing static files

Parameters:
  EnvironmentName:
    Type: String
    Description: "S3 for Static File Storage"

Resources:
  StaticFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'opensupports-static-${AWS::StackName}-${EnvironmentName}' #Refers to the name of the CloudFormation stack in which the S3 bucket is being created
      VersioningConfiguration:
        Status: Enabled
      

  StaticFilesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref StaticFilesBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject" #Restricts the public to only be able to read (GET) the objects, not write or delete
            Resource: !Sub 'arn:aws:s3:::${StaticFilesBucket}/*' 

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref StaticFilesBucket
