AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket for storing static files

Resources:
  StaticFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'opensupports-static-${AWS::StackName}-${EnvironmentName}'
      
      VersioningConfiguration:
        Status: Enabled
   StaticFilesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref StaticFilesBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub 'arn:aws:s3:::${StaticFilesBucket}/*'


    

